### ISSUE TITLE
need your help in swin transformer

### ISSUE THREAD

**Issue by fayezalhussein** [pateltanvi2992/EfficientSwin-A-Hybrid-Model-for-Blood-Cell-Classification-with-saliency-maps-visualization#1]
hello dear, How can I communicate with you? i am struggling with combined swin and vgg16

**Comment by pateltanvi2992** [comment]
> hello dear, How can I communicate with you? i am struggling with combined swin and vgg16

Hello, To switch from **EfficientNet** to **VGG** in my code, several key changes are required. First off, you'll need to import VGG from **torchvision.model**s, which offers a range of pre-trained models, in contrast to timm that includes a wider selection such as EfficientNet. After importing, you should revise the CustomHybridModel class to create a VGG instance instead of an EfficientNet one. This involves not just switching the model instantiation code but also revising the variable that captures the size of the features, given the discrepancy in feature output sizes between VGG and EfficientNet. Adjusting this is vital to ensure that the classifier that follows is fed inputs of the appropriate size. Implementing these changes will effectively reconfigure your code to harness VGG for extracting image features, making the most of its unique structural benefits and pre-trained strengths.

I hope this help.

**Comment by fayezalhussein** [comment]
i will try it. thank you so much

**Comment by fayezalhussein** [comment]
Can I return back to you after trying it?

**Comment by pateltanvi2992** [comment]
Please, let me know if that helps. So, I will close this issue. Thanks.

**Comment by fayezalhussein** [comment]
yeah thank you so much, i appreciate your help
